name: test-unary-union-bug

on:
  # run on all pushes to any branch
  push:
  # also run periodically
  schedule:
    - cron: "41 7 15 * *"
jobs:
  test:
    name: Test for unary bug
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install with poetry
        run: poetry install
      - name: Test with pytest
        run: poetry run pytest -v

